name: 'Update Website'
description: 'Updates the website with a pull request'
inputs:
  repo:
    description: 'the repo that contains the website'
    required: true
  branch:
    description: 'the base branch in the website repo'
    required: true
  user:
    description: 'the username of the pull request author'
    required: true
  email:
    description: 'the email of the pull request author'
    required: true
runs:
  using: 'node22'
  main: 'dist/index.js'
